CREATE DATABASE IF NOT EXISTS myBookShelfPBO;
USE myBookShelfPBO;

CREATE TABLE IF NOT EXISTS myBook (
    isbn INT NOT NULL PRIMARY KEY,
    judul VARCHAR(50) NOT NULL,
    penulis VARCHAR(50) NOT NULL,
    penerbit VARCHAR(50) NOT NULL,
    tahun INT NOT NULL,
    sekarang INT NOT NULL DEFAULT 0,
    total INT NOT NULL,
    STATUS TINYINT(1) NOT NULL DEFAULT 0,
    favorite TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);